[font]
size = 12.0

[window]
opacity = 0.7


[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[shell]
program = "/usr/bin/bash"

[window.padding]
x = 20
y = 20
